work_directory: &work_directory
  working_directory: ~/utilities

orbs:
  templates: devatherock/circleci-templates@0.7.0

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:2023.04.2
    resource_class: medium
    <<: *work_directory

version: 2.1
jobs:
  test:
    executor: machine-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/utilities
      - restore_cache:
          keys:
            - v1-integration-{{ checksum "build.gradle" }}
            - v1-integration-
      - run: |
          make integration-test
      - store_artifacts:
          path: build/reports
      - store_test_results:
          path: build/test-results
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-integration-{{ checksum "build.gradle" }}

workflows:
  version: 2.1
  build:
    jobs:
      - templates/slack:
          name: notify
          context:
            - docker-credentials
            - slack-webhook
          filters:
            branches:
              only: master
      - test:
          context:
            - docker-credentials
          requires:
            - notify

  pr_check:
    jobs:
      - test:
          context:
            - docker-credentials
          filters:
            branches:
              ignore:
                - master